title: NimbleSim 
description: Documentation for the NimbleSim Unity Package.
theme: just-the-docs

url: https://just-the-docs.github.io

# Replace this later with links to the package and social links.
# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "/assets/images/icon.png"

color_scheme: nimble

collections:
  getting-started:
    output: true
  tutorials:
    output: true
  concepts:
    output: true
  examples:
    output: true
  api-reference:
    output: true

just_the_docs:
  collections:
    getting-started:
      name: getting started
    tutorials:
      name: tutorials
    concepts:
      name: concepts
    examples:
      name: examples
    api-reference:
      name: api-reference

callouts:
  note:
    title: Note
    color: teal
  warning:
    title: Warning
    color: red
