title: NimbleSim 
description: Documentation for the NimbleSim Unity Package.
theme: just-the-docs

url: https://just-the-docs.github.io

# Replace this later with links to the package and social links.
# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

logo: "/assets/images/icon.png"

color_scheme: nimble

collections:
  getting-started:
    output: true
  concepts:
    output: true
  examples:
    output: true

just_the_docs:
  collections:
    getting-started:
      name: getting started
    concepts:
      name: concepts
    examples:
      name: examples

